# Generated by Django 5.1.6 on 2025-02-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('petrol_type', models.CharField(max_length=10)),
            ],
        ),
    ]
