# Generated by Django 5.1.6 on 2025-02-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelpurchase',
            name='total_points',
        ),
        migrations.AddField(
            model_name='customer',
            name='total_points',
            field=models.FloatField(default=0),
        ),
    ]
