# Generated by Django 5.1.6 on 2025-02-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_fuelpurchase_total_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='unique_id',
            field=models.CharField(default=1, editable=False, max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
