# Generated by Django 5.1.6 on 2025-02-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customer_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Foydalanuvchi ismi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_points',
            field=models.FloatField(default=0, verbose_name='Jami ballar'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='unique_id',
            field=models.CharField(editable=False, max_length=7, unique=True, verbose_name='Foydalanuvchi ID'),
        ),
    ]
